### ISSUE TITLE
reek 3 roadmap

### ISSUE THREAD

**Issue by troessner** [troessner/reek#401]
## We agreed on the following minimum feature set for reek 3

Breaking changes to 2:

- [x] Drop ruby 1.9 support
- [x] Coming from #422 : shaping what is and what is not part of the ‘public API’

Not necessarily breaking changes:

- [ ] Fix all known bugs
- [ ] Make reek more rails-friendly or add a "rails" mode. For instance our reek configuration file is full of excludes for "respond_to" blocks.

## reek 4 / reek 3 (but not required)

- [ ] Add cool and innovative smells. I think @mvz already suggested something like an UnusedCode smell.
- [ ] Smell-freeness in our codebase (and / or ignoring found smells that are "ok" for us)
- [ ] Additional smells (All of those are still up for discussion):
  - Inappropriate intimacy: a class that has dependencies on implementation details of another class.
  - Refused bequest: a class that overrides a method of a base class in such a way that the contract of the base class is not honored by the derived class. See Liskov substitution principle.
  - Lazy class / Freeloader: a class that does too little.
  - LoD violations
  - Code Calisthenics

**Comment by chastell** [comment]
Should we strive for no smells in the reek’s codebase as well? :)

**Comment by troessner** [comment]
Ah, good idea, I like that @chastell !

**Comment by andyw8** [comment]
I'd love a option to automatically generate a configuration 'todo' file like RuboCop has:

https://github.com/bbatsov/rubocop#automatically-generated-configuration

**Comment by mvz** [comment]
I like the 'Rails mode'.

I'm less sure about the todo option. It would have to be quite different from the RuboCop option, for two reasons:
* We have just simplified our configuration to only allow one file. We could add in 'include' directive, but that would need separate justification.
* There's a lot of interaction between different code smells, so in general it seems to me it's better to tackle files or classes one by one rather than smells (except for a few like IrresponsibleModule).
I'm not against it, but we really need to think about how people should use it.

**Comment by troessner** [comment]
>> We have just simplified our configuration to only allow one file. We could add in 'include' directive, but that would need separate justification.

Quite frankly, I don't think this is a good idea. Wouldn't we then re-introduce the complexity we want to get rid of? 
The key idea was that using multiple configuration files in reek is an edge case and doesnt make sense in most cases - i think we should stick with this.

**Comment by troessner** [comment]
@mvz @chastell I updated the issue description with all we agreed on until now, feel free to edit at will.:)

**Comment by chastell** [comment]
> feel free to edit at will

This was too tempting, so I turned them into checkboxen. :ballot_box_with_check:

**Comment by troessner** [comment]
Even better!..:)

**Comment by chastell** [comment]
How about we drop Ruby 1.9 support in reek 3? Ruby 1.9 is no longer maintained and Ruby 2.0 brings keyword arguments, which I find quite useful now and then. (Better yet, Ruby 2.1 brings required keyword arguments.)

**Comment by troessner** [comment]
Good idea @chastell, +1 from my side.

**Comment by troessner** [comment]
I would throw 3 additional smells in the mix which i think would be awesome!

- Inappropriate intimacy: a class that has dependencies on implementation details of another class.
- Refused bequest: a class that overrides a method of a base class in such a way that the contract of the base class is not honored by the derived class. See Liskov substitution principle.
- Lazy class / Freeloader: a class that does too little.

(from http://en.wikipedia.org/wiki/Code_smell)

**Comment by andyw8** [comment]
For 'Inappropriate Intimacy', do you mean checking for LOD violations, or something more?

(I see @kevinrutherford [considered supporting LOD](https://github.com/troessner/reek/issues/11) in the past but decided against it).

**Comment by chastell** [comment]
@troessner: do you think any of these seem simple enough / good candidates for (start of) implementation at [ROSSConf Vienna](http://www.rossconf.io)? The last one seems to be a good candidate if we can define what it means.

**Comment by troessner** [comment]
>>  do you think any of these seem simple enough / good candidates for (start of) implementation at ROSSConf Vienna? The last one seems to be a good candidate if we can define what it means.

I believe "Lazy class" could be fairly easy.

>> For 'Inappropriate Intimacy', do you mean checking for LOD violations, or something more?

Yes, exactly.

>> (I see @kevinrutherford considered supporting LOD in the past but decided against it).

Yes, I know. I still think it would be very nice to have and the user can always disable the smell if he disagrees.:)

**Comment by andyw8** [comment]
I think LOD checks would be difficult one to implement with static analysis. For example, with Rails scopes, `Widget.available.by_name` is not an LOD violation since ActiveRecord uses a fluent interface.

A simpler alternative might be the 'one dot per line' rule from [Object Calisthenics](http://williamdurand.fr/2013/06/03/object-calisthenics/)?

**Comment by chastell** [comment]
I just want to note that Law of Demeter is not about the number of dots and all about type boundaries – e.g., if something returns an `Array` then it’s perfectly fine to tag a chain of functional transformations on it. :)

**Comment by troessner** [comment]
@chastell yes, I believe @andyw8 was just suggesting a pragmatic compromise that wouldn't really cover LoD but at least hint at that something might be wrong.
Regarding LoD: Of the top of my head I have zero idea how to do that in a dynamic language.:)

**Comment by troessner** [comment]
Alrightie, I updated the issue and I'm confident I integrated all of your suggestions. The smells are still all up for discussion, but let's do that in separate issues rather.

**Comment by nTraum** [comment]
I'd like to add the following feature request to the list:

Report about unused exclusions. We have a couple of reek configuration files that have beefy `exclude` lists. Keeping the list up to date, is quite a struggle, as code is constantly being refactoring, meaning classes change, methods change etc. The most prominent example would be: Class / method that has been added to the exclusion list doesn't even exist anymore in the code base.

The only option you have right now is to do this manually and I wonder if this could be automated. Implementations could be:

* separate rake task that prints out 'unused' exclusions
* config option (`-- fail-on-unused-exclusions`), so that this could be directly integrated into your normal reek run.

WDYT?

**Comment by nTraum** [comment]
> Make reek more rails-friendly or add a "rails" mode. For instance our reek configuration file is full of excludes for "respond_to" blocks.

Another common one: Automatically exclude helpers from the `UtilityFunction` smell. All helper methods will have that smell by definition (if you use Rails helpers like they're 'supposed' to be used).

**Comment by andyw8** [comment]
:+1: Reek isn't so Rails-friendly with the out-of-the-box configuration.

**Comment by troessner** [comment]
>> Another common one: Automatically exclude helpers from the UtilityFunction smell. All helper methods will have that smell by definition (if you use Rails helpers like they're 'supposed' to be used).

....which would be part of the mega-awesome rails-mode already listed above! ;)

**Comment by chastell** [comment]
> Report about unused exclusions

A big :+1: on this from me – I actually had this at the back of my head, but assumed that it bothers only me when my `reek` config files collect cruft…

**Comment by troessner** [comment]
>> A big :+1: on this from me – I actually had this at the back of my head, but assumed that it bothers only me when my reek config files collect cruft…

Yes, we obviously have a need for that. Care for a PR @nTraum ?.:)

**Comment by troessner** [comment]
Looking at the list from above this is a huge and absurd roadmap. Not that I don't like it but if we implement all-the-things then it's gonna be 2017.:)

How about just doing:

* Drop ruby 1.9 support
* Coming from #422 : shaping what is and what is not part of the ‘public API’
* Fix all known bugs
* Make reek more rails-friendly or add a "rails" mode. 

as minimum requirement for reek 3?

Everything else I'd leave up for reek 4. Or we just do them when we want to (i mean, we're doing reek because it's fun for us, not because we must stick to a roadmap), but not as minimum requirement for reek 3.

Let me know what you think about this!

**Comment by chastell** [comment]
:+1: – I think the above are what’s  important/breaking in `reek` 3; new smells and smell-free `reek` codebase can just as well come as incremental feature 3.x releases.

**Comment by mvz** [comment]
Agreed. This new list makes a lot of sense. Even rails mode can be in a minor release since it won't break existing use.

**Comment by troessner** [comment]
Great, I'll create issues for the things we agreed on will label them with reek-3.:)

**Comment by troessner** [comment]
Addendum @mvz : For me its not only about "breaking changes" but also working towards one common goal as a team.:)

**Comment by mvz** [comment]
@troessner of course :-).

By the way, what's your reason for not using `develop` to work toward reek 3.0 on? Do you think we should make another 2.x release first?

**Comment by troessner** [comment]
>> By the way, what's your reason for not using develop to work toward reek 3.0 on? Do you think we should make another 2.x release first?

Looking at our huuuuuuuge reek-3 roadmap back then  I thought it would be a good idea to give us some room for 2.x releases in between.
But now that we shrunk down our roadmap and are more or less already working on it I can see that this doesn't make much sense anymore.

How about just dropping the reek-3 branch completely and re-opening and then merging #530 ?

**Comment by mvz** [comment]
> How about just dropping the reek-3 branch completely and re-opening and then merging #530 ?

Good idea. I'll get on it.

**Comment by mvz** [comment]
> I'll get on it.

Right. Hit a snag: The remote branch is gone. I'll rebase reek-3 onto develop instead and preserve merges.

**Comment by chastell** [comment]
:+1: I thought gitflow’s approach is ‘`develop` is the most forward-looking branch, everything else lives on release branches’ – so in this case `reek` 3 should indeed live on `develop` and if we want to roll `reek` 2.2.2 or `reek` 2.3.0 we’ll just branch at an earlier point for the release.

**Comment by troessner** [comment]
But as soon as there is #530 in "develop" there is no "proper", non-hacky way of doing another 2.x release or am i missing something @chastell?

**Comment by chastell** [comment]
I don’t think `git checkout -b releases/2.2 0ed1703` and/or `git checkout -b releases/2.3 0ed1703` (0ed1703 being the last non-`reek`-3 commit on `develop`) are very hacky and we can do them anytime. :)

**Comment by troessner** [comment]
>> I don’t think git checkout -b release/2.2 0ed1703 and/or git checkout -b release/2.3 0ed1703 (0ed1703 being the last non-reek-3 commit on develop) are very hacky

That's exactly what I'd call hacky. Our workflow and release model is built around branches, not SHA's (I'm aware that a branch is not much more than a fancy pointer to a certain SHA but that is besides the point).
The very second we make exceptions and deviate from our simple branching and release model it's hacky.

So let's rather have a separate feature branch for reek-4.:)

**Comment by chastell** [comment]
> That's exactly what I'd call hacky.

Then we should’ve had branched `release/2.3` (or `reek-2.3`) before merging the first `reek` 3 feature to `develop`. :)

(But we can just as well do that anytime as per my above comment and no-one will know!) ;)

> So let's rather have a separate feature branch for reek-4.:)

So what should `develop` mean?
* ‘2.2 – the one we might have bugfixes for’? (No, we should either have `release/2.2` or say that since 2.2.0 we just have `master` for this.)
* ‘2.3 – the one we might have new features for’? (But we’re not sure we’ll have them, and we can just as well have `release/2.3` for this.)
* ‘3.0 – the furthest release we started working on’? (This is the current state after `reek-3` got merged to `develop`.)

With a separate `reek-4` branch we’ll have to decide one day that `reek` 3 is done and merge `reek-4` to `develop`. On the other hand, it’s convenient to branch from and open PRs against the default, so `develop` should probably just represent the current minor version (be it 2.3 or 3.0) we want new features for. What _is_ the `reek` version we want new features for? :)

**Comment by troessner** [comment]
>> What is the reek version we want new features for? :)

Well, we can also just decide as a team that we are going for a major release and won't allow minor releases, then this whole problem goes away we can just continue like we're doing now with using develop.:)

**Comment by chastell** [comment]
> we can also just decide as a team that we are going for a major release

![I’m ok with this](http://i.stack.imgur.com/YW0X6.png)

**Comment by troessner** [comment]
:)

**Comment by mvz** [comment]
Looks like we hit our first snag using git flow: It doesn't have a prescribed way of working on a major version while also putting out minor releases of the previous major.

I can think of all kinds of ways to deal with this, but for now let's just get reek 3 out the door and worry about reek 4 when we've accumulated plans for enough breaking changes again.

**Comment by troessner** [comment]
>> It doesn't have a prescribed way of working on a major version while also putting out minor releases of the previous major.

True, but we mitigate this by just having a feature branch (like reek-3) that contains all the breaking features and that we update with "develop" periodically.

>> I can think of all kinds of ways to deal with this, but for now let's just get reek 3 out the door and worry about reek 4 when we've accumulated plans for enough breaking changes again.

Also an excellent plan.:)

**Comment by troessner** [comment]
I'd suggest to implement the 2 breaking changes from above:

[1] Drop ruby 1.9 support
[2] Coming from #422 : shaping what is and what is not part of the ‘public API’

the first one we have already and I guess @mvz will take care of [2]..:)
And then lets just release reek 3. This would also allow us to release bugfixes like #539 into the wild which are right now blocked (we could merge / cherry-pick them into master separately but that probably will become tedious very quick. #539 already has some merge conflicts and the tests fail).

**Comment by mvz** [comment]
Sounds good. I'll pick up #422 again.

**Comment by troessner** [comment]
>> Sounds good. I'll pick up #422 again.

You mean #528 - right?..:)

**Comment by mvz** [comment]
> You mean #528 - right?..:)

Yes :-).

**Comment by troessner** [comment]
Api feature has been merged!

I'd release this little honeybadger!

Objections?

**Comment by chastell** [comment]
None from me, as long as we’re explicit and check the relevant checkboxen at the top of this issue – I think we punted on all of the optional ideas and the Rails mode, right?

**Comment by troessner** [comment]
>> None from me, as long as we’re explicit and check the relevant checkboxen at the top of this issue 

Just did that.:)

>> I think we punted on all of the optional ideas and the Rails mode, right?

Yes! But this can be right the next thing we're going for with 3.1.:)

**Comment by chastell** [comment]
Let’s roll then! :tada:

**Comment by mvz** [comment]
:+1: :tada:

**Comment by troessner** [comment]
And released it is!
Closing this one! 
Regarding all the ideas above, I'll just create a new issue for this so we don't forget about it.
